# Generated by Django 5.0.4 on 2024-04-16 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customers',
            table='Customer',
        ),
    ]
